import 'dotenv/config';
import Stripe from 'stripe';
import { handleChargeEvent } from './forwardTransfer';

const exampleChargeUpdatedEvent = {
  id: 'evt_1QFDYbQM2dPzRG2KONstvIY9',
  object: 'event',
  api_version: '2017-04-06',
  created: 1730201153,
  data: {
    object: {
      id: 'py_1QFDYaQM2dPzRG2K0JdkKTJa',
      object: 'charge',
      amount: 1174,
      amount_captured: 1174,
      amount_refunded: 0,
      application: 'ca_R5F59pcP7A69okJBl6jYZ89nUHl7IRVf',
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_1QFDYbQM2dPzRG2KFBHkbRpD',
      billing_details: {
        address: {
          city: null,
          country: null,
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: null,
        name: null,
        phone: null,
      },
      calculated_statement_descriptor: null,
      captured: true,
      created: 1730201153,
      currency: 'gbp',
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {
        sellerStripeAccountId: 'acct_1QClJ1BHXYXKy5wR',
        orderUuid: '74f75272-4957-4314-8903-755ca404e734',
      },
      on_behalf_of: null,
      order: null,
      outcome: null,
      paid: true,
      payment_intent: null,
      payment_method: null,
      payment_method_details: {
        stripe_account: {},
        type: 'stripe_account',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUUNqblJRTTJkUHpSRzJLKMGMg7kGMgYCXyxDSFc6LBbHepUl-QeGc11UqdzLdqPbj5NP8ElPJWiwejoFaVNB9f43TOVTHwF1lKLQ',
      refunded: false,
      refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/py_1QFDYaQM2dPzRG2K0JdkKTJa/refunds',
      },
      review: null,
      shipping: null,
      source: {
        id: 'acct_1QCjnwQPHZlbUQp1',
        object: 'account',
        application_name: null,
      },
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
    previous_attributes: {},
  },
  livemode: false,
  pending_webhooks: 2,
  request: 'req_rjD0ijlWYhMUCi',
  type: 'charge.updated',
} as any as Stripe.Event;

handleChargeEvent(exampleChargeUpdatedEvent);
